/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPostsIndexRouteImport } from './routes/api/posts/index'
import { Route as ApiPostsPincodeRouteImport } from './routes/api/posts/$pincode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIndexRoute = ApiPostsIndexRouteImport.update({
  id: '/api/posts/',
  path: '/api/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsPincodeRoute = ApiPostsPincodeRouteImport.update({
  id: '/api/posts/$pincode',
  path: '/api/posts/$pincode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/posts/$pincode': typeof ApiPostsPincodeRoute
  '/api/posts/': typeof ApiPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/posts/$pincode': typeof ApiPostsPincodeRoute
  '/api/posts': typeof ApiPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/posts/$pincode': typeof ApiPostsPincodeRoute
  '/api/posts/': typeof ApiPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/posts/$pincode' | '/api/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/posts/$pincode' | '/api/posts'
  id: '__root__' | '/' | '/api/posts/$pincode' | '/api/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPostsPincodeRoute: typeof ApiPostsPincodeRoute
  ApiPostsIndexRoute: typeof ApiPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/': {
      id: '/api/posts/'
      path: '/api/posts'
      fullPath: '/api/posts/'
      preLoaderRoute: typeof ApiPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$pincode': {
      id: '/api/posts/$pincode'
      path: '/api/posts/$pincode'
      fullPath: '/api/posts/$pincode'
      preLoaderRoute: typeof ApiPostsPincodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPostsPincodeRoute: ApiPostsPincodeRoute,
  ApiPostsIndexRoute: ApiPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
